CREATE TABLE Meat(
	MeatId INTEGER PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(10)

)

CREATE TABLE [Role](
	RoleId INTEGER PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50)
)

CREATE TABLE [User](
	UserId INTEGER PRIMARY KEY IDENTITY(1,1),
	RoleId INTEGER,
	UserName VARCHAR(50),
	Email VARCHAR(50),
	Gender VARCHAR(50),
	[Password] VARCHAR(50),
	FOREIGN KEY (RoleId) REFERENCES [Role](RoleId)

)

CREATE TABLE [Header](
	HeaderId INTEGER PRIMARY KEY IDENTITY(1,1),
	UserId INTEGER,
	StaffId INTEGER,
	[Date] DATE,
	FOREIGN KEY (UserId) REFERENCES [User](UserId)
)

CREATE TABLE Ramen(
	RamenId INTEGER PRIMARY KEY IDENTITY(1,1),
	MeatId INTEGER,
	[Name] VARCHAR(50),
	Borth VARCHAR(50),
	Price INTEGER,
	FOREIGN KEY (MeatId) REFERENCES Meat(MeatId)
)

CREATE TABLE Detail(
	DetailID INTEGER PRIMARY KEY IDENTITY(1,1),
	HeaderId INTEGER,
	RamenId INTEGER,
	Quantity INTEGER,
	FOREIGN KEY (HeaderId) REFERENCES Header(HeaderId),
	FOREIGN KEY (RamenId) REFERENCES Ramen(RamenId)
)

CREATE TABLE Cart(
	CartId INTEGER PRIMARY KEY IDENTITY(1,1),
	RamenId INTEGER,
	UserId INTEGER,
	Quantity INTEGER,
	FOREIGN KEY (RamenId) REFERENCES Ramen(RamenId),
	FOREIGN KEY (UserId) REFERENCES [User](UserId)
)